.PHONY: clean All

All:
	@echo "----------Building project:[ CodingQuestions - Debug ]----------"
	@cd "CodingQuestions" && "$(MAKE)" -f  "CodingQuestions.mk"
clean:
	@echo "----------Cleaning project:[ CodingQuestions - Debug ]----------"
	@cd "CodingQuestions" && "$(MAKE)" -f  "CodingQuestions.mk" clean
